image: bdadamas24/node-xvfb:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy
  # - documentation

before_script:
  - npm install -s

# pages:
#   stage: documentation
#   script:
#     - npm run grunt docs
#   artifacts:
#     paths:
#       - public
#   only:
#     - master
#     - develop
#

build:
  stage: build
  only:
    - master
    - develop
  script:
    - npm run build
  artifacts:
    paths:
      - dist

test:
  stage: test
  only:
    - master
    - develop
  script:
    # - sh -e /etc/init.d/xvfb start
    # - sleep 3 # give xvfb some time to start
    # - apt-get install -y libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev
    # - export DISPLAY=':99:0'
    - apt-get install libxss1
    # - xvfb-run npm run test2
    # - xvfb-run --server-num=10 npm run test
    - xvfb-run npm run test

deploy:
  stage: deploy
  only:
    - master
    - develop
  script:
    - cd deploy
    - npm install -s
    - node ./deploy_to_s3.js ../dist showcar-ads/$CI_BUILD_REF_NAME/$CI_BUILD_REF showcar-ads.html
    - node ./deploy_to_s3.js ../dist showcar-ads/$CI_BUILD_REF_NAME/latest showcar-ads.html
    # - node ./deploy_to_s3.js ../src/html showcar-ui showcar-ui-fragment.html

    # - node ./deploy_to_s3.js "../dist/+(showcar-ads.html|index.js)" showcar-ads/$CI_BUILD_REF_NAME/$CI_BUILD_REF
    # - node ./deploy_to_s3.js "../dist/showcar-ads.html" showcar-ads/$CI_BUILD_REF_NAME/latest
    # - node deploy/deploy_to_s3.js "src/html/showcar-ui-fragment.html" showcar-ui
