image: bdadamas24/node-xvfb:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

before_script:
  - npm install -s

test:
  stage: test
  only:
    - master
    - develop
  script:
    - xvfb-run npm run test

build:
  stage: build
  only:
    - master
    - develop
  script:
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - master
    - develop
  script:
    - cd deploy
    - npm install -s
    - node ./deploy_to_s3.js ../dist showcar-ads/$CI_BUILD_REF_NAME/$CI_BUILD_REF showcar-ads.html
    - node ./deploy_to_s3.js ../dist showcar-ads/$CI_BUILD_REF_NAME/latest showcar-ads.html
