image: bdadamas24/node-xvfb:latest

# cache:
#   paths:
#     - node_modules/

stages:
  # - install
  - test
  - build
  - deploy
  # - documentation

before_script:
  # - apt-get install libxss1
  - npm install -s

# install:
#   stage: install
#   cache:
#     key: "$CI_BUILD_REF_NAME"
#     paths:
#       - node_modules/
#   only:
#     - master
#     - develop
#   script:
#     - npm install -s


build:
  stage: build
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
  only:
    - master
    - develop
  script:
    - npm run build
  artifacts:
    paths:
      - dist

test:
  stage: test
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
  only:
    - master
    - develop
  script:
    - xvfb-run npm run test

deploy:
  stage: deploy
  only:
    - master
    - develop
  script:
    - cd deploy
    - npm install -s
    - node ./deploy_to_s3.js ../dist showcar-ads/$CI_BUILD_REF_NAME/$CI_BUILD_REF showcar-ads.html
    - node ./deploy_to_s3.js ../dist showcar-ads/$CI_BUILD_REF_NAME/latest showcar-ads.html
